### ISSUE TITLE
지도 움직일 시, 탈출구 세부 정보 확인시 등 브라우저와 상호작용하면 매우 심한 끊김 발생

### ISSUE THREAD

**Issue by Bluebear645** [karpitony/eft-where-am-i#18]
브라우저에서 하드웨어 가속이 지원되는지 확인해봐야할것같습니다
따로 코드를 보진 않았지만 가장 먼저 확인해보면 좋을거같네요

**Comment by Bluebear645** [comment]
Webview에서 따로 하드웨어 가속을 지원하지 않고, Chrome에서 그래픽 가속 끄고 태스트 해보았을때 같은 증상이 발견되지 않는걸 보면 아마도 하드웨어 가속 문제는 아닌거같습니다. 코드 문제인지 아니면 외부 라이브러리를 바꿔야 해결될 문제인지 알아봐야겠네요,,

**Comment by 5tarlight** [comment]
[v2.0-beta](https://github.com/karpitony/eft-where-am-i/releases/tag/v2.0-beta)
에서 C#으로 마이그레이션하여 해결되었습니다.
