### ISSUE TITLE
전체적 UI/UX 편의성 / 가시성 개선

### ISSUE THREAD

**Issue by Bluebear645** [karpitony/eft-where-am-i#24]
### 상단 네비게이션 바 관련 개선점
![image](https://github.com/karpitony/eft-where-am-i/assets/51251138/ed4fae93-5873-4676-b5d9-2c45206ffb03)

- 앱을 전체화면으로 사용시 상단 바 공간을 효율적으로 사용하지 않음 (오른쪽 빈 공간 생김)
  - 버튼 배열을 크기에 따라 가로로 늘려 배치함으로 반응형 UI 구성으로 공간 활용 가능
- 레이드시 상단 버튼을 사용하는 경우는 적음으로 상단 바를 수납할 수 있는 기능
- 자동으로 지도가 전체화면 (Full screen 버튼) 모드로 켜질 수 있는 기능

### ~~맵 선택관련 편의성 개선~~ (해결)
- 마지막으로 선택한 맵 저장 및 다음 실행시에 자동으로 불러오는 기능 
  - 시작시 기본으로 선택되는 그라운드제로는 초반 이후 잘 가지 않는 맵이라 편의성이 떨어짐
  - 보통 레이드시 퀘스트를 깨는 등의 이유로 같은 맵을 연이어 가는 경우가 많아 관련 기능 필요

**Comment by karpitony** [comment]
자세한 개선 의견 감사합니다. 상단 바를 접어서 보관한다는 건 좋은 아이디어 같아 다음 버전에 반영해보도록 하겠습니다. 그런데 이전 선택 맵이 자동으로 불러와지는 기능은 이미 2.0 베타 버전에  적용했었는데, 혹시 그 기능이 정상적으로 작동하지 않고 있나요? 그 부분 한번 확인 부탁드립니다.

**Comment by Bluebear645** [comment]
확인했더니 잘 작동하네요!! 처음 실행하고 재실행해본적이 한번도 없고 릴리즈노트에도 안써있어서 추가된지 몰랐습니다 ㅋㅋㅋ

**Comment by 5tarlight** [comment]
릴리즈 노트에 추가했습니다.

**Comment by karpitony** [comment]
@Bluebear645

[v2.0](https://github.com/karpitony/eft-where-am-i/releases/tag/v2.0)에서 상단바 접기와 맵 전체화면 시작 기능을 포함한 새로운 업데이트를 출시했습니다. 현재 자동 전체화면 기능은 기본 설정으로 적용되어 있지만, 추후 버전에서는 사용자가 설정을 통해 켜고 끌 수 있도록 할 예정입니다. 윈폼의 한계와 제가 윈폼에 익숙하지 않아서 반응형 디자인은 구현하기 어려울 것 같습니다. 

프로젝트에 대한 지속적인 관심과 적극적인 의견 감사합니다. 좋은 하루 되세요.

**Comment by Bluebear645** [comment]
제가 C계열 언어를 못해 도움은 못드리지만 편리한 앱 개발 감사드립니다. 앞으로도 기대하겠습니다
